openapi: 3.0.0
info:
  title: Exemple d'API
  description: Une simple API pour démontrer OpenAPI.
  version: 1.0.0
paths:
  /utilisateurs:
    get:
      summary: Liste des utilisateurs
      description: Récupère la liste des utilisateurs avec leurs informations.
      parameters:
        - name: age
          in: query
          required: false
          description: Filtrer les utilisateurs par âge.
          schema:
            type: integer
            example: 30
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Requête invalide
components:
  schemas:
    Utilisateur:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nom:
          type: string
          example: Dupont
        age:
          type: integer
          example: 30
